// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:826ac5d6-cb83-4d1f-839f-27f074756671",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_VUjuGfWIR",
    "aws_user_pools_web_client_id": "4dqvf48ldbbt1f4c7d6h82sba5",
    "oauth": {},
    "aws_content_delivery_bucket": "amplify-console-20190713182713-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://amplify-console-20190713182713-hostingbucket-dev.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
